-- Insert 100 sample todos into the Todo table
INSERT INTO "Todo" (id, title, text, completed) VALUES
(1, 'Laundry', 'Wash and dry clothes from the past week', 0),
(2, 'Grocery Shopping', 'Buy milk, eggs, bread, and vegetables', 1),
(3, 'Call Mom', 'Check in and catch up on the week', 0),
(4, 'Finish Project Report', 'Complete Q4 quarterly report for review', 1),
(5, 'Schedule Doctor Appointment', 'Book annual checkup for next month', 0),
(6, 'Water Plants', 'Give all indoor plants a good watering', 0),
(7, 'Pay Electric Bill', 'Submit payment before deadline', 1),
(8, 'Organize Garage', 'Sort and arrange tools and equipment', 0),
(9, 'Review Code Changes', 'Check pull requests from team members', 0),
(10, 'Prepare Presentation', 'Create slides for upcoming meeting', 1),
(11, 'Fix Leaky Faucet', 'Repair bathroom sink before it gets worse', 0),
(12, 'Update Resume', 'Add recent projects and achievements', 0),
(13, 'Meal Prep Sunday', 'Prepare meals for the entire week', 1),
(14, 'Clean Windows', 'Wash interior and exterior windows', 0),
(15, 'Write Blog Post', 'Publish article on new technology trends', 0),
(16, 'Backup Important Files', 'Create backup of documents and photos', 1),
(17, 'Bike Maintenance', 'Oil chain and check tire pressure', 0),
(18, 'Learn Spanish', 'Complete Duolingo daily lesson', 0),
(19, 'Submit Expense Report', 'File reimbursement for business travel', 1),
(20, 'Car Oil Change', 'Schedule appointment at service center', 0),
(21, 'Organize Closet', 'Donate old clothes and reorganize', 0),
(22, 'Read Chapter 3', 'Continue reading technology book', 1),
(23, 'Debug Login Issue', 'Fix authentication problem in app', 0),
(24, 'Send Thank You Cards', 'Write notes to recent hosts', 0),
(25, 'Renew Car Insurance', 'Update policy before expiration', 1),
(26, 'Walk Dog', 'Take morning walk around neighborhood', 0),
(27, 'Update Software', 'Install latest system updates', 0),
(28, 'Plan Vacation', 'Research destinations and book flights', 1),
(29, 'Dentist Appointment', 'Regular cleaning and checkup', 0),
(30, 'Create Wireframes', 'Design new user interface for app', 0),
(31, 'Water Lawn', 'Set sprinklers for evening watering', 1),
(32, 'Catch Up on Emails', 'Process inbox and respond to messages', 0),
(33, 'Fix Broken Link', 'Update website navigation issue', 0),
(34, 'Schedule Team Meeting', 'Set up quarterly planning session', 1),
(35, 'Vacuum Carpet', 'Clean living room and bedrooms', 0),
(36, 'Refactor Database Query', 'Optimize slow SQL performance', 0),
(37, 'Buy Birthday Gift', 'Shop for friends upcoming party', 1),
(38, 'Update Password Manager', 'Change weak and old passwords', 0),
(39, 'Prepare for Interview', 'Practice technical questions', 0),
(40, 'Clean Kitchen', 'Scrub counters and appliances', 1),
(41, 'Deploy to Production', 'Release new version to live servers', 0),
(42, 'Trim Hedges', 'Cut back overgrown garden hedges', 0),
(43, 'Create Unit Tests', 'Write tests for new functions', 1),
(44, 'Buy Office Supplies', 'Stock up on notebooks and pens', 0),
(45, 'Review Analytics', 'Check website traffic and metrics', 0),
(46, 'Paint Bedroom Wall', 'Refresh room with new color', 1),
(47, 'Update Documentation', 'Write API documentation for team', 0),
(48, 'Return Library Books', 'Check due dates and make returns', 0),
(49, 'Fix CSS Layout', 'Resolve responsive design issues', 1),
(50, 'Buy Groceries', 'Get ingredients for dinner recipes', 0),
(51, 'Attend Web Meeting', 'Join quarterly business review', 0),
(52, 'Organize Tax Documents', 'Gather receipts for accountant', 1),
(53, 'Install New Shelves', 'Mount storage in office', 0),
(54, 'Review Contract', 'Read and approve legal document', 0),
(55, 'Download Updates', 'Install security patches', 1),
(56, 'Walk to Park', 'Get fresh air and exercise', 0),
(57, 'Fix Broken Button', 'Repair UI component in app', 0),
(58, 'Buy New Phone Case', 'Protect device from damage', 1),
(59, 'Attend Training Session', 'Learn new software framework', 0),
(60, 'Wash Car', 'Clean exterior and vacuum interior', 0),
(61, 'Update Build Pipeline', 'Configure CI/CD automation', 1),
(62, 'Prune Tree', 'Remove dead branches carefully', 0),
(63, 'Implement Feature', 'Develop new dashboard feature', 0),
(64, 'Buy House Plants', 'Add greenery to living space', 1),
(65, 'Setup Monitoring', 'Configure system health alerts', 0),
(66, 'Organize Photos', 'Backup and sort picture library', 0),
(67, 'Refill Prescriptions', 'Pick up medication from pharmacy', 1),
(68, 'Test API Endpoints', 'Verify all routes are working', 0),
(69, 'Replace Light Bulbs', 'Change burnt out bulbs throughout', 0),
(70, 'Write Unit Tests', 'Cover edge cases in code', 1),
(71, 'Visit Dentist', 'Get teeth cleaned and checked', 0),
(72, 'Optimize Database', 'Add indexes to improve queries', 0),
(73, 'Buy Winter Clothes', 'Purchase warm jacket and boots', 1),
(74, 'Debug Network Issue', 'Investigate connectivity problem', 0),
(75, 'Clean Basement', 'Organize storage and declutter', 0),
(76, 'Create API Documentation', 'Write comprehensive user guide', 1),
(77, 'Attend Gym', 'Complete workout routine', 0),
(78, 'Fix Performance Issue', 'Reduce app load time', 0),
(79, 'Buy Birthday Cake', 'Order dessert for celebration', 1),
(80, 'Review Pull Request', 'Check code quality and approve', 0),
(81, 'Patch Drywall', 'Fill holes and smooth wall', 0),
(82, 'Implement Authentication', 'Add login system to website', 1),
(83, 'Buy Office Chair', 'Replace uncomfortable seating', 0),
(84, 'Migrate Database', 'Move to new server infrastructure', 0),
(85, 'Arrange Furniture', 'Rearrange living room layout', 1),
(86, 'Add Error Handling', 'Improve exception management', 0),
(87, 'Buy Garden Tools', 'Get equipment for yard work', 0),
(88, 'Deploy Hotfix', 'Release critical bug fix', 1),
(89, 'Organize Kitchen Cabinets', 'Arrange dishes and containers', 0),
(90, 'Add Logging', 'Implement detailed logging system', 0),
(91, 'Buy Printer Ink', 'Replace empty cartridges', 1),
(92, 'Refactor Code', 'Improve code structure and clarity', 0),
(93, 'Clean Bathroom', 'Scrub tiles and fixtures', 0),
(94, 'Setup Docker', 'Containerize application', 1),
(95, 'Buy Cleaning Supplies', 'Stock up on household items', 0),
(96, 'Add Caching Layer', 'Implement Redis for performance', 0),
(97, 'Trim Lawn', 'Cut grass to appropriate height', 1),
(98, 'Write Integration Tests', 'Test component interactions', 0),
(99, 'Buy Gifts for Family', 'Shop for upcoming holidays', 0),
(100, 'Finalize Release Notes', 'Document all version changes', 1);
